### ISSUE TITLE
Unique on columns which are composite key

### ISSUE THREAD

**Issue by ibeladi-mrsool** [usernane/phMysql#11]
### Problem
When using 2 or more columns as a composite key (using isPrimary function). All the columns receive the unique property which is wrong and leads to errors. 

### Purposed solution
Remove the unique property from the columns upon receiving the primary property if there are 2 or more columns unless specified otherwise which is unlikely.

**Comment by usernane** [comment]
The bug was fixed in [This Commit](https://github.com/usernane/phMysql/commit/9177e06d39c2d69001452292283b65680e615719). Thanks for reporting.
